"""added unavailabilities

Revision ID: 44ae8f802d44
Revises: cbdff1c94a27
Create Date: 2025-08-28 15:53:19.818679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44ae8f802d44'
down_revision: Union[str, Sequence[str], None] = 'cbdff1c94a27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unavailabilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('start_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.CheckConstraint('end_utc > start_utc', name=op.f('ck_unavailabilities_ck_unavail_time_order')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_unavailabilities_employee_id_employees'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_unavailabilities'))
    )
    with op.batch_alter_table('unavailabilities', schema=None) as batch_op:
        batch_op.create_index('ix_unavail_emp_start_end', ['employee_id', 'start_utc', 'end_utc'], unique=False)
        batch_op.create_index(batch_op.f('ix_unavailabilities_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_unavailabilities_end_utc'), ['end_utc'], unique=False)
        batch_op.create_index(batch_op.f('ix_unavailabilities_start_utc'), ['start_utc'], unique=False)

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_employees_email'), ['email'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_employees_email'), type_='unique')

    with op.batch_alter_table('unavailabilities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_unavailabilities_start_utc'))
        batch_op.drop_index(batch_op.f('ix_unavailabilities_end_utc'))
        batch_op.drop_index(batch_op.f('ix_unavailabilities_employee_id'))
        batch_op.drop_index('ix_unavail_emp_start_end')

    op.drop_table('unavailabilities')
    # ### end Alembic commands ###
