"""'schema fixes

Revision ID: cbdff1c94a27
Revises: e621bda9069e
Create Date: 2025-08-26 17:33:39.753404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbdff1c94a27'
down_revision: Union[str, Sequence[str], None] = 'e621bda9069e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employees_email'))
        batch_op.create_unique_constraint(batch_op.f('uq_employees_email'), ['email'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_employees_email'), type_='unique')
        batch_op.create_index(batch_op.f('ix_employees_email'), ['email'], unique=False)

    # ### end Alembic commands ###
