"""initial schema

Revision ID: e621bda9069e
Revises: 66ae1c128d9d
Create Date: 2025-08-26 17:15:55.274228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e621bda9069e'
down_revision: Union[str, Sequence[str], None] = '66ae1c128d9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_hours', sa.Integer(), nullable=False))
        batch_op.drop_column('maxHours')

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_name'))
        batch_op.create_unique_constraint(None, ['name'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('ix_roles_name'), ['name'], unique=1)

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('maxHours', sa.INTEGER(), nullable=False))
        batch_op.drop_column('max_hours')

    # ### end Alembic commands ###
